[build]
  functions = "lambda-functions"
  publish = "dist"

[[redirects]]
  from = "/"
  to = "/.netlify/functions/app/"
  status = 200

[context.production]
  environment = { NODE_VERSION = "14.15.0" }

[template.environment]
  FAUNADB_SERVER_SECRET = "Your FaunaDB server Secret"
  WEATHER_KEY = "Your Open Weather Map api key"
  ROLLBAR_BE_ACCESS_TOKEN = "Your backend node.js rollbar access token"
